### ISSUE TITLE
Cypress: OpenAI E2E tests passes locally but not on CI

### ISSUE THREAD

**Issue by dandyson** [dandyson/waygenie#40]
The 'openAI-e2e.cy.js' test file passes locally, but I cannot get any of the tests to pass in the CI pipeline.
 
Not even the spinner (which should be on the page straight away) seems to appear. The test cannot seem to find anything at all

There can be a number of reasons, stated in this doc  - https://docs.cypress.io/faq/questions/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

* ISSUE LOG FROM GITHUB ACTIONS RUN: 

  Running:  openAi-e2e.cy.js                                                          

  OpenAI API Call
    1) displays a spinner while the API is being called
    2) displays itinerary events after API response
    3) displays an error message if the OpenAI request fails
  0 passing (26s)
  3 failing
  1) OpenAI API Call
       displays a spinner while the API is being called:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `div[role="status"]`, but never found it.
      at Context.eval (webpack://***-frontend/./cypress/e2e/openAi-e2e.cy.js:57:53)

  2) OpenAI API Call
       displays itinerary events after API response:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `getItinerary`. No request ever occurred.
https://on.cypress.io/wait
      at cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:76025:18)
      at Object.errByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:76079:10)
      at checkForXhr (http://localhost:3000/__cypress/runner/cypress_runner.js:135700:84)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:135726:28)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:144102:68)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144043:14)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack://***-frontend/./cypress/e2e/openAi-e2e.cy.js:98:7)

  3) OpenAI API Call
       displays an error message if the OpenAI request fails:
     CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `openAIRequestFail`. No request ever occurred.
https://on.cypress.io/wait
      at cypressErr (http://localhost:3000/__cypress/runner/cypress_runner.js:76025:18)
      at Object.errByPath (http://localhost:3000/__cypress/runner/cypress_runner.js:76079:10)
      at checkForXhr (http://localhost:3000/__cypress/runner/cypress_runner.js:135700:84)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:135726:28)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:144102:68)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:144043:14)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack://***-frontend/./cypress/e2e/openAi-e2e.cy.js:120:7)

  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────
  │ Tests:        3                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      3                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  3                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     26 seconds                                                                       │
  │ Spec Ran:     openAi-e2e.cy.js                                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────

**Comment by dandyson** [comment]
Resolved in #46
